#!/usr/bin/perl
#! -*- perl -*-

#
# Author: Cassie E Nicol cassieenicol@gmail.com
#
# An Arch Linux Live CD can be downloaded here for testing
# https://www.archlinux.org/download/
    
use strict;
use warnings;

use Data::Dumper;

use Getopt::Long qw(:config no_ignore_case bundling pass_through no_auto_abbrev );

use Pod::Usage;

#------------------------------------------------------------------------

my $debug = undef;

#------------------------------------------------------------------------
# Define the command line options for GetOpt::Long

# Define the operations
my %operations = (
    'database|D' => \&database,
    'query|Q'    => \&query,
    'remove|R'   => \&remove,
    'sync|S'     => \&sync,
    'deptest|T'  => \&deptest,
    'files|F'    => \&files,
    'version|V'  => \&version,
    'help'       => \&help,
    );

# Define the Operation Options (not used)
my %operation_options = (
    'database|D',
    'query|Q',
    'remove|R',
    'sync|S',
    'deptest|T',
    'files|F',
    'version|V',
    'help',
    );

# Define the Standard Options
my @standard_options = (
    'dbpath|b=s',
    'verbose|v',
    'arch=s',
    'cachedir=s',
    'color=s',
    'config',
    'debug',
    'gpgdir=s',
    'hookdir=s',
    'logfile=s',
    'noconfirm',
    'confirm',
    'disable_download_timeout',
    'sysroot=s',
    );

# Define Database Options
my @database_options = (
    'asdeps=s',
    'asexplicit=s',
    'check|k',
    'quiet|q',
    );

# Define the Query Options
my @query_options = (
    'changelog|c',
    'deps|d',
    'explicit|e',
    'groups|g',
    'info|i',
    'check|k',
    'list|l',
    'foreign|m',
    'native|n',
    'owns|o=s',
    'file|p',
    'quiet|q',
    'search|s=s',
    'unrequired|t',
    'upgrades|u',
    );

# Define Remove Options (apply to -R)
my @remove_options = (
'cascade|c',
'nosave|n',
'recursive|s',
'unneeded|u',
    );

# Define the Sync Options
my @sync_options = (
    'clean|c',
    'groups|g',
    'info|i',
    'list|l',
    'quiet|q',
    'search|s=s',
    'sysupgrade|u',
    'downloadonly|w',
    'refresh|y+',
    );

# Define Transaction Options (apply to -S, -R, and -U)
my @transaction_options = (
    'nodeps|d',
    'assume-installed=s',
    'dbonly',
    'noprogressbar',
    'noscriptlet',
    'print|p',
    'print-format=s',
    );

# Define Upgrade Options (apply to -S and -U)
my @upgrade_options = (
    'asdeps',
    'asexplicit',
    'ignore=s',
    'ignoregroup=s',
    'needed',
    'overwrite=s',
    );

# Define File Options (apply to -F)
my @file_options = (
    'refresh|y',
    'list|l',
    'search|s',
    'regex|x',
    'owns|o',
    'quiet|q',
    'machinereadable',
    );

#------------------------------------------------------------------------
# Debug to show on console a bar of dashes when the app starts.

print "------------------------------------------------------------------------------\n";
print "$0 @ARGV\n";

#------------------------------------------------------------------------
# Save a copy of the command line

my @command_line = @ARGV;
print "command_line:\n", Dumper \@command_line if($debug);

#------------------------------------------------------------------------
# Define Globals

# Operation to execute
my $operation;

# Options to use based upon the operation
my @options = @standard_options;

# Options found    
my %option_hash = ();

#------------------------------------------------------------------------
# Determine the Operation

my $p = Getopt::Long::Parser->new;
$p->configure( 'no_ignore_case', 'bundling', 'pass_through', 'no_auto_abbrev' );
$p->getoptions(%operations);
die "Operation not given." if( ! defined $operation );

print "\@ARGV:\n", Dumper(\@ARGV) if($debug);

#------------------------------------------------------------------------
# Get Options

my $o = Getopt::Long::Parser->new;
#$o->configure( 'no_ignore_case', 'bundling', 'pass_through', 'no_auto_abbrev' );
$o->configure( 'no_ignore_case', 'bundling', 'no_auto_abbrev' );
$o->getoptions(\%option_hash, @options);

if(1) {
    #print "option_hash:\n", Dumper(\%option_hash);
    print Data::Dumper->Dump([\%option_hash], [qw(*option_hash)]);
    print Data::Dumper->Dump([\@ARGV], ['*argv']);
} else {
    print("Options Found\n");
    for my $key (keys %option_hash ) {
	print("$key");
	print(": $option_hash{$key}") if( defined $option_hash{$key} );
	print("\n");
    }
}

#------------------------------------------------------------------------
# Run operation

&{$operation}();

exit(0);

#------------------------------------------------------------------------
# Utility functions

sub print_values {
    my ($opt_name, $opt_value) = @_;
    $opt_name = 'undef' if( ! defined $opt_name );
    $opt_value = 'undef' if( ! defined $opt_value );
    print("${opt_name}, ${opt_value}\n");
}

#------------------------------------------------------------------------

sub database {
    print_values(@_);
    $operation = \&do_database;
    push(@options, @database_options);
}

sub do_database {
    print("do_database()\n");
}

sub query {
    print_values(@_);
    $operation = \&do_query;
    push(@options, @query_options);
}

sub do_query {
    print("do_query()\n");
}

sub remove {
    print_values(@_);
    $operation = \&do_remove;
    push(@options, @remove_options);
    push(@options, @transaction_options);
}

sub do_remove {
    print "do_remove()\n";
}

sub sync {
    print_values(@_);
    $operation = \&do_sync;
    push(@options, @sync_options);
    push(@options, @transaction_options);
    push(@options, @upgrade_options);
}

sub do_sync {
    print("do_sync()\n");
}

sub deptest {
    my ($opt_name, $opt_value) = @_;
    $operation = \&do_deptest;
}

sub do_deptest {
    print "do_deptest()\n";
}

sub upgrade {
    print_values(@_);
    $operation = \&do_upgrade;
    push(@options, @upgrade_options);
    push(@options, @transaction_options);
}

sub do_upgrade {
    print "do_upgrade()\n";
}

sub files {
    print_values(@_);
    $operation = \&do_files;
    push(@options, @file_options);
}

sub do_files {
    print "do_files()\n";
}

sub version {
    print_values(@_);
    $operation = \&do_version;
}

sub do_version {
    print "do_version()\n";
}

sub help {
    print_values(@_);
    $operation = \&do_help;
    #%options = (%options, @help_options);
}

sub do_help {
    pod2usage(1);
}

#(fset 'print-variable
#   [?  ?  ?  ?  ?p ?r ?i ?n ?t ?\( ?\" right ?\C-k left ?Y backspace ?\C-y ?: ?  ?\C-e ?\{ ?\C-y ?\} ?\\ ?n ?\" ?\) ?\; right])

# Getopt::Long encourages the use of Pod::Usage to produce help messages. For example:

__END__

=head1 NAME

sample - Using Getopt::Long and Pod::Usage

=head1 SYNOPSIS

sample [options] [file ...]

 Options:
   -help            brief help message
   -man             full documentation

=head1 OPTIONS

=over 8

=item B<-help>

Print a brief help message and exits.

=item B<-man>

Prints the manual page and exits.

=back

=head1 DESCRIPTION

B<This program> will read the given input file(s) and do something
useful with the contents thereof.

=cut
